// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRuYPUc5nO7tJHvoL38i4PiASINqoz20w',
    appId: '1:391572737407:web:c43f0d2b9ec50ce9c9de4a',
    messagingSenderId: '391572737407',
    projectId: 'gatbi-84114',
    authDomain: 'gatbi-84114.firebaseapp.com',
    storageBucket: 'gatbi-84114.firebasestorage.app',
    measurementId: 'G-HPRP6ETKZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7Q_ajXdH0XVAectPLff7jYrh6Bar9T8I',
    appId: '1:391572737407:android:9a534a59e1952cf4c9de4a',
    messagingSenderId: '391572737407',
    projectId: 'gatbi-84114',
    storageBucket: 'gatbi-84114.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBAqlGdyaFxBlU3A8JMZWprSsJ6Qovmb8',
    appId: '1:391572737407:ios:df211d4dd704504fc9de4a',
    messagingSenderId: '391572737407',
    projectId: 'gatbi-84114',
    storageBucket: 'gatbi-84114.firebasestorage.app',
    iosBundleId: 'com.example.taskProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBAqlGdyaFxBlU3A8JMZWprSsJ6Qovmb8',
    appId: '1:391572737407:ios:df211d4dd704504fc9de4a',
    messagingSenderId: '391572737407',
    projectId: 'gatbi-84114',
    storageBucket: 'gatbi-84114.firebasestorage.app',
    iosBundleId: 'com.example.taskProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRuYPUc5nO7tJHvoL38i4PiASINqoz20w',
    appId: '1:391572737407:web:1480ccd73c0aaa0cc9de4a',
    messagingSenderId: '391572737407',
    projectId: 'gatbi-84114',
    authDomain: 'gatbi-84114.firebaseapp.com',
    storageBucket: 'gatbi-84114.firebasestorage.app',
    measurementId: 'G-YK4DWEGFF4',
  );
}
