class TopProductModel {
  const TopProductModel({
    required this.id,
    required this.name,
    this.imageUrl,
    this.paidOrders = 0,
    this.revenue = 0,
    this.currency = 'AED',
    this.sku,
  });

  final int id;
  final String name;

  final String? imageUrl;

  /// Number of paid orders containing this product.
  final int paidOrders;

  /// Revenue generated by this product.
  final double revenue;

  final String currency;

  final String? sku;

  TopProductModel copyWith({
    int? id,
    String? name,
    String? imageUrl,
    int? paidOrders,
    double? revenue,
    String? currency,
    String? sku,
  }) {
    return TopProductModel(
      id: id ?? this.id,
      name: name ?? this.name,
      imageUrl: imageUrl ?? this.imageUrl,
      paidOrders: paidOrders ?? this.paidOrders,
      revenue: revenue ?? this.revenue,
      currency: currency ?? this.currency,
      sku: sku ?? this.sku,
    );
  }

  factory TopProductModel.fromJson(Map<String, dynamic> json) {
    return TopProductModel(
      id: _parseInt(json['id']),
      name: json['name']?.toString() ?? '',
      imageUrl: json['image_url']?.toString() ?? json['imageUrl']?.toString(),
      paidOrders: _parseInt(json['paid_orders'] ?? json['paidOrders']),
      revenue: _parseDouble(json['revenue']),
      currency: json['currency']?.toString() ?? 'AED',
      sku: json['sku']?.toString(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'image_url': imageUrl,
      'paid_orders': paidOrders,
      'revenue': revenue,
      'currency': currency,
      'sku': sku,
    };
  }

  static int _parseInt(dynamic value) {
    if (value is int) return value;

    if (value is num) {
      return value.toInt();
    }

    return int.tryParse(value?.toString() ?? '') ?? 0;
  }

  static double _parseDouble(dynamic value) {
    if (value is double) return value;

    if (value is num) {
      return value.toDouble();
    }

    return double.tryParse(value?.toString() ?? '') ?? 0;
  }
}
